
name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - master
      # - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['12.0', '13.0', '14.0', '15.0', '16.0', '17.0', '18.0']
        php: ['7.3']
        archi: ['amd64']
        variant: ['fpm', 'fpm-alpine']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: Execute CI hooks
        id: docker_hooks
        run: |
          cd images/${{ matrix.version }}/php${{ matrix.php }}-${{ matrix.variant }}-${{ matrix.archi }}
          ./hooks/run

      - name: Display docker images
        run: docker images
